import { ArrowRight, BriefcaseBusiness, CheckCircle2, Clock3, FileWarning, LockKeyhole, UserRound } from 'lucide-react'
import { useState, type FormEvent } from 'react'

export type UserRole = 'client' | 'cpa'

export function LoginScreen({onLogin}:{onLogin:(role:UserRole,tenantId:string)=>void}) {
  const [role,setRole]=useState<UserRole>('client')
  const [email,setEmail]=useState('maya.flores@example.com')
  const [password,setPassword]=useState('demo123')
  const [error,setError]=useState('')
  const accounts={client:{email:'maya.flores@example.com',name:'Maya Flores',context:'2025 individual return'},cpa:{email:'jordan.lee@miraflorestax.com',name:'Jordan Lee, CPA',context:'MiraFlores Tax · Tax preparer'}}
  function choose(next:UserRole){setRole(next);setEmail(accounts[next].email);setPassword('demo123');setError('')}
  function submit(event:FormEvent){event.preventDefault();if(email.toLowerCase()!==accounts[role].email||password!=='demo123'){setError('Email or password does not match this MiraFlores Tax account.');return}onLogin(role,'miraflores-tax')}
  return <div className="login-page"><section className="login-brand"><div className="login-logo">M</div><div><span>MiraFlores Tax</span><small>Secure tax collaboration</small></div><p>One secure platform for clients and the tax professionals who serve them.</p></section><main className="login-main"><div className="login-card"><div className="tenant-banner"><span className="login-logo small">M</span><div><small>TAX FIRM WORKSPACE</small><strong>MiraFlores Tax</strong><span>Workspace ID: miraflores-tax</span></div></div><div className="login-copy"><div className="eyebrow">TENANT-SPECIFIC SIGN IN</div><h1>Welcome back.</h1><p>Sign in to your MiraFlores Tax workspace.</p></div><div className="login-role-tabs"><button className={role==='client'?'selected':''} onClick={()=>choose('client')}><UserRound size={16}/>Client</button><button className={role==='cpa'?'selected':''} onClick={()=>choose('cpa')}><BriefcaseBusiness size={16}/>CPA</button></div><div className="selected-account"><span className={`account-icon ${role==='cpa'?'dark':''}`}>{role==='cpa'?<BriefcaseBusiness/>:<UserRound/>}</span><span className="account-info"><small>{role==='cpa'?'TAX FIRM ACCOUNT':'CLIENT ACCOUNT'}</small><strong>{accounts[role].name}</strong><span>{accounts[role].context}</span></span></div><form className="login-form" onSubmit={submit}><label>Email address<input type="email" value={email} onChange={event=>setEmail(event.target.value)} autoComplete="username"/></label><label>Password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete="current-password"/></label>{error&&<div className="login-error" role="alert">{error}</div>}<button className="login-submit" type="submit">Sign in as {role==='cpa'?'CPA':'client'} <ArrowRight size={17}/></button></form><div className="demo-credentials"><strong>Sample credentials</strong><span>{accounts[role].email}</span><span>Password: demo123</span></div><p className="login-note"><LockKeyhole size={14}/>This account can access only the MiraFlores Tax tenant. Authentication is simulated.</p></div></main></div>
}

const clients = [
  {id:'flores-2025',name:'Maya & Daniel Flores',type:'Individual · 2025',status:'Needs review',detail:'1 extracted value flagged',tone:'urgent'},
  {id:'thompson-2025',name:'Amara Thompson',type:'Individual · 2025',status:'Waiting on client',detail:'2 document requests open',tone:'waiting'},
  {id:'rowan-2025',name:'Rowan Street Studio LLC',type:'Business · 2025',status:'In preparation',detail:'Updated 34 minutes ago',tone:'normal'},
]

export function CpaDashboard({onReview}:{onReview:(client:{id:string;name:string})=>void}) {
  const [query,setQuery]=useState('')
  const [statusFilter,setStatusFilter]=useState('all')
  const normalizedQuery=query.trim().toLowerCase()
  const visibleClients=clients.filter(client=>(statusFilter==='all'||client.status===statusFilter)&&client.name.toLowerCase().includes(normalizedQuery))
  const filters=[{status:'Needs review',label:'Need review',icon:FileWarning},{status:'Waiting on client',label:'Waiting on clients',icon:Clock3},{status:'In preparation',label:'In preparation',icon:CheckCircle2}]
  return <div className="cpa-dashboard"><div className="eyebrow">CPA WORKSPACE</div><div className="cpa-welcome"><div><h1>Good morning, Jordan.</h1><p>Here’s the work that needs your attention today.</p></div><span>Monday · August 23</span></div><section className="metric-row" aria-label="Filter clients by status">{filters.map(filter=>{const Icon=filter.icon;const count=clients.filter(client=>client.status===filter.status).length;return <button key={filter.status} className={statusFilter===filter.status?'selected':''} onClick={()=>setStatusFilter(statusFilter===filter.status?'all':filter.status)} aria-pressed={statusFilter===filter.status}><Icon/><div><strong>{count}</strong><span>{filter.label}</span></div></button>})}</section><section className="work-queue"><div className="queue-heading"><div><h2>Your assigned clients</h2><p>Only returns assigned to Jordan Lee are shown</p></div><div className="queue-controls"><label><span className="sr-only">Search clients by name</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search by client name"/></label><button className={statusFilter==='all'?'selected':''} onClick={()=>setStatusFilter('all')}>All assigned</button></div></div>{visibleClients.length?visibleClients.map(client=><button className="client-row" key={client.id} onClick={()=>onReview({id:client.id,name:client.name})}><span className="client-initials">{client.name.split(' ').slice(0,2).map(x=>x[0]).join('')}</span><span className="client-name"><strong>{client.name}</strong><small>{client.type}</small></span><span className={`queue-status ${client.tone}`}>{client.status}</span><span className="client-detail">{client.detail}</span><ArrowRight size={17}/></button>):<div className="queue-empty"><strong>No clients found</strong><span>Try another name or clear the selected status.</span></div>}</section></div>
}
