import { ArrowRight, BriefcaseBusiness, CheckCircle2, Clock3, FileWarning, LockKeyhole, UserRound } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'

export type UserRole = 'client' | 'cpa'

export function LoginScreen({onLogin}:{onLogin:(role:UserRole,tenantId:string)=>void}) {
  const [role,setRole]=useState<UserRole>('client')
  const [email,setEmail]=useState('maya.flores@example.com')
  const [password,setPassword]=useState('demo123')
  const [error,setError]=useState('')
  const accounts={client:{email:'maya.flores@example.com',name:'Maya Flores',context:'2025 individual return'},cpa:{email:'jordan.lee@miraflorestax.com',name:'Jordan Lee, CPA',context:'MiraFlores Tax · Tax preparer'}}
  function choose(next:UserRole){setRole(next);setEmail(accounts[next].email);setPassword('demo123');setError('')}
  function submit(event:FormEvent){event.preventDefault();if(email.toLowerCase()!==accounts[role].email||password!=='demo123'){setError('Email or password does not match this MiraFlores Tax account.');return}onLogin(role,'miraflores-tax')}
  return <div className="login-page"><section className="login-brand"><div className="login-logo">M</div><div><span>MiraFlores Tax</span><small>Secure tax collaboration</small></div><p>One secure platform for clients and the tax professionals who serve them.</p></section><main className="login-main"><div className="login-card"><div className="tenant-banner"><span className="login-logo small">M</span><div><small>TAX FIRM WORKSPACE</small><strong>MiraFlores Tax</strong><span>Workspace ID: miraflores-tax</span></div></div><div className="login-copy"><div className="eyebrow">TENANT-SPECIFIC SIGN IN</div><h1>Welcome back.</h1><p>Sign in to your MiraFlores Tax workspace.</p></div><div className="login-role-tabs"><button className={role==='client'?'selected':''} onClick={()=>choose('client')}><UserRound size={16}/>Client</button><button className={role==='cpa'?'selected':''} onClick={()=>choose('cpa')}><BriefcaseBusiness size={16}/>CPA</button></div><div className="selected-account"><span className={`account-icon ${role==='cpa'?'dark':''}`}>{role==='cpa'?<BriefcaseBusiness/>:<UserRound/>}</span><span className="account-info"><small>{role==='cpa'?'TAX FIRM ACCOUNT':'CLIENT ACCOUNT'}</small><strong>{accounts[role].name}</strong><span>{accounts[role].context}</span></span></div><form className="login-form" onSubmit={submit}><label>Email address<input type="email" value={email} onChange={event=>setEmail(event.target.value)} autoComplete="username"/></label><label>Password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete="current-password"/></label>{error&&<div className="login-error" role="alert">{error}</div>}<button className="login-submit" type="submit">Sign in as {role==='cpa'?'CPA':'client'} <ArrowRight size={17}/></button></form><div className="demo-credentials"><strong>Sample credentials</strong><span>{accounts[role].email}</span><span>Password: demo123</span></div><p className="login-note"><LockKeyhole size={14}/>This account can access only the MiraFlores Tax tenant. Authentication is simulated.</p></div></main></div>
}

type ReturnItem={id:string;name:string;type:string;status:'Needs review'|'Waiting on client'|'In preparation'|'Ready to file';owner:string;task:string;dueDays:number;blocked:boolean;unread:number;priority:number;tone:string}
const firstNames=['Amara','Noah','Sophia','Ethan','Olivia','Mateo','Ava','Lucas','Mia','Elijah','Isla','Henry','Nora','Leo','Zoe','James','Layla','Owen']
const lastNames=['Thompson','Chen','Patel','Garcia','Williams','Kim','Brown','Nguyen','Davis','Wilson','Martinez','Clark']
const owners=['Jordan Lee','Priya Shah','Marcus Reed','Elena Ruiz']
const statuses:ReturnItem['status'][]=['Needs review','Waiting on client','In preparation','Ready to file']
function rank(item:Omit<ReturnItem,'priority'|'tone'>){return (item.dueDays<=1?60:item.dueDays<=3?35:item.dueDays<=7?15:0)+(item.blocked?25:0)+(item.status==='Needs review'?20:item.status==='Ready to file'?12:0)+Math.min(item.unread*4,16)}
function makeReturn(index:number):ReturnItem{
  const status=statuses[index%statuses.length],dueDays=(index*7)%31,blocked=index%9===0,unread=index%5,owner=owners[index%owners.length]
  const business=index%6===0,name=business?`${lastNames[index%lastNames.length]} ${['Creative','Consulting','Foods','Studio'][index%4]} LLC`:`${firstNames[index%firstNames.length]} ${lastNames[(index*5)%lastNames.length]}`
  const task=status==='Needs review'?'Review flagged tax value':status==='Waiting on client'?'Follow up on document request':status==='Ready to file'?'Approve return for filing':'Complete return preparation'
  const base={id:`return-${index}`,name,type:`${business?'Business':'Individual'} · 2025`,status,owner,task,dueDays,blocked,unread}
  const priority=rank(base);return {...base,priority,tone:priority>=70?'urgent':status==='Waiting on client'?'waiting':'normal'}
}
const clients:ReturnItem[]=[{id:'flores-2025',name:'Maya & Daniel Flores',type:'Individual · 2025',status:'Needs review',owner:'Jordan Lee',task:'Verify federal withholding',dueDays:0,blocked:true,unread:3,priority:121,tone:'urgent'},...Array.from({length:179},(_,index)=>makeReturn(index+1))]
function priorityLabel(item:ReturnItem){return item.priority>=90?'Critical':item.priority>=70?'High':item.priority>=40?'Medium':'Routine'}
export function CpaDashboard({onReview}:{onReview:(client:{id:string;name:string})=>void}) {
  const [query,setQuery]=useState('')
  const [statusFilter,setStatusFilter]=useState('all')
  const [priorityFilter,setPriorityFilter]=useState('all')
  const [limit,setLimit]=useState(20)
  const normalizedQuery=query.trim().toLowerCase()
  const scoped=useMemo(()=>clients.filter(client=>client.owner==='Jordan Lee'),[])
  const ranked=useMemo(()=>scoped.filter(client=>(statusFilter==='all'||client.status===statusFilter)&&(priorityFilter==='all'||priorityLabel(client).toLowerCase()===priorityFilter)&&client.name.toLowerCase().includes(normalizedQuery)).sort((a,b)=>b.priority-a.priority||a.dueDays-b.dueDays),[scoped,statusFilter,priorityFilter,normalizedQuery])
  const filters=[{status:'Needs review',label:'Need review',icon:FileWarning},{status:'Waiting on client',label:'Waiting on clients',icon:Clock3},{status:'Ready to file',label:'Ready to file',icon:CheckCircle2}]
  return <div className="cpa-dashboard"><div className="dashboard-topline"><div><div className="eyebrow">CPA WORKSPACE</div><h1>What should I work on right now?</h1></div></div><section className="metric-row" aria-label="Filter returns by status">{filters.map(filter=>{const Icon=filter.icon;const count=scoped.filter(client=>client.status===filter.status).length;return <button key={filter.status} className={statusFilter===filter.status?'selected':''} onClick={()=>{setStatusFilter(statusFilter===filter.status?'all':filter.status);setLimit(20)}} aria-pressed={statusFilter===filter.status}><Icon/><div><strong>{count}</strong><span>{filter.label}</span></div></button>})}</section><section className="work-queue"><div className="queue-heading queue-heading-controls"><div className="queue-controls"><label><span className="sr-only">Search returns by client name</span><input type="search" value={query} onChange={event=>{setQuery(event.target.value);setLimit(20)}} placeholder="Search returns"/></label><label><span className="sr-only">Filter by priority</span><select value={priorityFilter} onChange={event=>{setPriorityFilter(event.target.value);setLimit(20)}}><option value="all">All priorities</option><option value="critical">Critical priority</option><option value="high">High priority</option><option value="medium">Medium priority</option><option value="routine">Routine priority</option></select></label></div></div>{ranked.length?<><div className="action-queue-head"><span>Client / next action</span><span>Status</span><span>Deadline</span><span/></div>{ranked.slice(0,limit).map(client=><button className="client-row action-row" key={client.id} onClick={()=>onReview({id:client.id,name:client.name})}><span className="client-name"><strong>{client.name}</strong><small>{client.task}</small></span><span className={`queue-status ${client.tone}`}>{client.status}</span><span className="client-detail">{client.dueDays===0?'Due today':`Due in ${client.dueDays}d`}</span><ArrowRight size={17}/></button>)}{limit<ranked.length&&<button className="load-more" onClick={()=>setLimit(value=>value+20)}>Show 20 more <span>{ranked.length-limit} remaining</span></button>}</>:<div className="queue-empty"><strong>No returns found</strong><span>Try another search or priority filter.</span></div>}</section></div>
}
